theme: minima
title: Cowes Garden Room
description: Passivhaus inspired garden room
author: tobi vogel
header_pages:
  - plans/MASTER_PLAN.md
  - plans/WORKPLAN.md
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
