theme: minima
title: Garden Room Plans
description: Passivhaus inspired garden room plans.
author: "tobi vogel"
header_pages:
  - plans/MASTER_PLAN_SIPS.md
  - plans/WORKPLAN_SIPS.md
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
